name: 'CI Workflow'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  required_ci:
    name: 'required-ci'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout 📦'
        uses: actions/checkout@v4

      - name: 'Setup Node 🟢'
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: 'Install dependencies 📚'
        run: yarn install --frozen-lockfile

      - name: 'Lint 🔍'
        run: yarn lint

      - name: 'Build 🧱'
        run: yarn -s build

      - name: 'Status message ✅'
        run: echo "✅ All CI checks passed"
